### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by rennemannd** [UFWebApps/MERN-Template#3]
This project is being setup with the client and the backend on the same project directory which means deployment may be more difficult onto Heroku since we will have two ports to deploy to. We need to ensure that any required resources for deploying to Heroku are either:

- Relevant resources linked in the README
OR
- Heroku deployment script pre-implemented

**Comment by Seth10001** [comment]
How was this solved?

**Comment by Seth10001** [comment]
jk I see it in the readme now - `production: Since the config file is not pushed when you deploy your app, you must specifiy your db uri in heorku. Set the uri in heroku as specified in this resource. Make sure you name the environement variable "DB_URI".`
